In [10]:
#Подсчет среднего значения фрактальной размерности и среднего абсолютного отклоления для каждого пользователя
import pandas as pd

In [18]:
file_path = "assets/fractal.csv"
data = pd.read_csv(file_path)

data['subject_number'] = data['image'].str.extract(r'finger_(\d+)_\d+.png') # Извлечение номера испытуемого из названия файла

average_dimensions = data.groupby('subject_number')['fractal_dimension'].mean().reset_index()
data['average_dimensions'] = data.groupby('subject_number')['fractal_dimension'].transform('mean')
data['mad'] = (data['fractal_dimension'] - data['average_dimensions']).abs()
user_mad = data.groupby('subject_number')['mad'].mean().reset_index()
data.head(-1)

,image,fractal_dimension,subject_number,average_dimensions,mad
0,finger_1_1.png,1.821180,1,1.825312,0.004132
1,finger_1_2.png,1.821963,1,1.825312,0.003349
2,finger_1_3.png,1.827314,1,1.825312,0.002003
3,finger_1_4.png,1.827825,1,1.825312,0.002513
4,finger_1_5.png,1.828276,1,1.825312,0.002965
...,...,...,...,...,...
249,finger_50_5.png,1.824113,50,1.822242,0.001871
250,finger_51_1.png,1.828950,51,1.828517,0.000433
251,finger_51_2.png,1.828961,51,1.828517,0.000444
252,finger_51_3.png,1.828558,51,1.828517,0.000042
253,finger_51_4.png,1.828350,51,1.828517,0.000166

In [16]:
user_mad.head(-1)

   subject_number       mad
0               1  0.002992
1              10  0.000932
2              11  0.001583
3              12  0.003192
4              13  0.001041
5              14  0.001128
6              15  0.003297
7              16  0.000542
8              17  0.001223
9              18  0.001076
10             19  0.000596
11              2  0.002669
12             20  0.001260
13             21  0.001059
14             22  0.002036
15             23  0.001679
16             24  0.002414
17             25  0.000373
18             26  0.002452
19             27  0.002747
20             28  0.001865
21             29  0.001016
22              3  0.001088
23             30  0.000583
24             31  0.002192
25             32  0.003103
26             33  0.003834
27             34  0.002115
28             35  0.002497
29             36  0.000666
30             37  0.002560
31             38  0.001059
32             39  0.002558
33              4  0.001439
34             40  0.001433
35             41  0.000582
36             42  0.000995
37             43  0.001444
38             44  0.002918
39             45  0.001774
40             46  0.001057
41             47  0.001325
42             48  0.001073
43             49  0.001655
44              5  0.002008
45             50  0.000748
46             51  0.000368
47              6  0.003145
48              7  0.001251
49              8  0.002077